# Generated by Django 5.2.1 on 2025-06-07 22:42

import django.db.models.deletion
import idioms.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idioms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpus",
            name="language",
            field=models.ForeignKey(
                default=idioms.models.get_default_language,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="idioms.language",
            ),
        ),
        migrations.AlterField(
            model_name="corpus",
            name="wordCount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="idiom",
            name="language",
            field=models.ForeignKey(
                default=idioms.models.get_default_language,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="idioms.language",
            ),
        ),
        migrations.AlterField(
            model_name="regex",
            name="idiom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="idioms.idiom"
            ),
        ),
    ]
