# Generated by Django 5.2.1 on 2025-06-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idioms", "0002_alter_corpus_language_alter_corpus_wordcount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpus",
            name="wordCount",
            field=models.IntegerField(),
        ),
    ]
