# Generated by Django 5.2.1 on 2025-07-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("idioms", "0003_alter_corpus_wordcount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Regex",
        ),
    ]
