# Generated by Django 5.2.1 on 2025-07-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idioms", "0004_delete_regex"),
    ]

    operations = [
        migrations.AddField(
            model_name="idiom",
            name="regex",
            field=models.TextField(null=True),
        ),
    ]
