# Generated by Django 5.2.1 on 2025-07-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idioms", "0005_idiom_regex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idiom",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
    ]
