# Generated by Django 5.2.1 on 2025-07-15 00:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idioms", "0006_alter_idiom_regex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corpus",
            old_name="wordCount",
            new_name="total_word_count",
        ),
        migrations.RemoveField(
            model_name="corpus",
            name="text",
        ),
        migrations.AddField(
            model_name="corpus",
            name="chunk_size_mb",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="corpus",
            name="chunks_directory",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="corpus",
            name="total_chunks",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SearchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("idiom_pattern", models.CharField(max_length=30)),
                ("is_completed", models.BooleanField(default=False)),
                ("failed_chunks", models.IntegerField(default=0)),
                ("completed_chunks", models.IntegerField(default=0)),
                ("total_matches", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="idioms.corpus"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_name", models.CharField(max_length=50)),
                ("failure_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "searchsession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="idioms.searchsession",
                    ),
                ),
            ],
        ),
    ]
