# Generated by Django 5.2.1 on 2025-07-25 02:36

import django.db.models.deletion
import idioms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idioms", "0007_rename_wordcount_corpus_total_word_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchsession",
            name="idiom_pattern",
        ),
        migrations.AddField(
            model_name="searchsession",
            name="idiom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="idioms.idiom",
            ),
        ),
        migrations.CreateModel(
            name="CustomRegex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regex", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        default=idioms.models.get_default_language,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="idioms.language",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="searchsession",
            name="custom_regex",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="idioms.customregex",
            ),
        ),
    ]
