# Generated by Django 5.2.1 on 2025-08-01 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idioms", "0008_remove_searchsession_idiom_pattern_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegexMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context_before", models.CharField(max_length=127)),
                ("match_text", models.CharField(max_length=63)),
                ("context_after", models.CharField(max_length=127)),
                (
                    "searchsession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="idioms.searchsession",
                    ),
                ),
            ],
        ),
    ]
