# Generated by Django 5.2.1 on 2025-08-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idioms", "0009_regexmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="p_hat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="p_hat_sigma",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
