# Generated by Django 5.2.1 on 2025-08-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idioms", "0010_searchsession_p_hat_searchsession_p_hat_sigma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customregex",
            name="regex",
            field=models.CharField(max_length=127),
        ),
    ]
